[package]
name = "requests-contract-wasm"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.multiversx-sc]
version = "0.54.0"
features = ["alloc"]

[dependencies]
requests-contract = { path = ".." }
