name: Golang Linter

on:
  push:
    branches: [ main, rc/*, feat/* ]
  pull_request:
      branches: [ main, rc/*, feat/* ]

jobs:
  golangci:
    name: Golang Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.24.11
      - uses: actions/checkout@v3
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --timeout 10m0s --max-issues-per-linter 0 --max-same-issues 0 --print-issued-lines

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go
          # skip-go-installation: true
